swagger: '2.0'
info:
  title: Health Monitoring Platform API
  version: 1.0.0
basePath: /api
schemes:
  - https
paths:
  /reports/generate:
    post:
      summary: Generate Report
      description: Generate a report for a given patient and date range.
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              patientId:
                type: string
              dateRange:
                type: object
                properties:
                  start:
                    type: string
                  end:
                    type: string
      responses:
        200:
          description: Report generated successfully.
        400:
          description: Invalid parameters.
