version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
networks:
  app-network:
    driver: bridge